# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0004_auto_20160918_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSectionPage1',
            fields=[
                ('pagenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.PageNode')),
                ('foo', models.CharField(max_length=8, verbose_name='Foo')),
            ],
            options={
                'abstract': False,
            },
            bases=('sections.pagenode',),
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
    ]
