# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 11:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20151220_1809'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('draft', django.db.models.manager.Manager()),
            ],
        ),
    ]
