# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_auto_20160927_1259"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagedynformfield",
            name="form_containing_model",
        ),
        migrations.DeleteModel(
            name="PageDynFormField",
        ),
    ]
