# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20160907_1122'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='included_form',
            field=models.CharField(blank=True, choices=[('dummy', 'dummy')], max_length=255, verbose_name='Included form'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, verbose_name='Slug'),
        ),
    ]
