# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuentry',
            name='slugs',
        ),
        migrations.AddField(
            model_name='menuentry',
            name='slug',
            field=models.CharField(blank=True, default='', help_text='Slug', max_length=512, verbose_name='slug'),
        ),
    ]
