# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_auto_20160908_1553"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autopopulated",
            options={
                "verbose_name": "Autopopulated Entry",
                "verbose_name_plural": "Autopoulated Entries",
            },
        ),
    ]
