# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_auto_20160911_1305"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autopopulated",
            options={
                "verbose_name": "Autopopulated Entry",
                "verbose_name_plural": "Autopopulated Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="viewlink",
            options={"verbose_name": "View", "verbose_name_plural": "View"},
        ),
    ]
