# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0005_auto_20160912_2314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewlink",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
