# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20161030_1520'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuentry',
            unique_together=set([]),
        ),
    ]
