# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentwidget",
            options={
                "verbose_name": "Simple Text Widget",
                "verbose_name_plural": "Simple Text Widgets",
            },
        ),
        migrations.AlterModelOptions(
            name="widgetinarea",
            options={
                "ordering": ["position"],
                "verbose_name": "Included widget",
                "verbose_name_plural": "Included widgets",
            },
        ),
    ]
