# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20160907_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleArticle',
            fields=[
                ('pagenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.PageNode')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'abstract': False,
            },
            bases=('sections.pagenode',),
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleSection',
            fields=[
                ('pagenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.PageNode')),
                ('node_type', models.CharField(blank=True, choices=[('dummy', 'dummy')], max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('sections.pagenode', models.Model),
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleSectionPage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('sections.pagenode',),
        ),
    ]
