# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_auto_20160912_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagenode',
            name='description',
            field=models.CharField(blank=True, help_text='Description (for searchengines)', max_length=139, verbose_name='Description'),
        ),
    ]
