# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-12 17:44
from __future__ import unicode_literals

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0005_auto_20161201_1704"),
    ]

    if django.VERSION >= (1, 9):
        operations = [
            migrations.AlterField(
                model_name="pagenode",
                name="slug",
                field=models.SlugField(
                    allow_unicode=True, max_length=255, verbose_name="Slug"
                ),
            ),
        ]
