# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-14 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoosableTemplateWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('name', models.SlugField(unique=True, verbose_name='name')),
                ('content', models.TextField(verbose_name='Content')),
                ('template', models.CharField(choices=[
                 ('widgets/baswidget.html', 'Base'), ('main/specialwidget.html', 'Special')], max_length=128, verbose_name='Template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
