# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='node_type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
