# Generated by Django 2.2.8 on 2019-12-25 12:53

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0008_auto_20191222_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('pagenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.PageNode')),
                ('content', models.TextField(verbose_name='Content')),
                ('teaser', models.TextField(verbose_name='Teaser')),
                ('image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('sections.pagenode',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('pagenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.PageNode')),
                ('node_type', models.CharField(blank=True, max_length=128)),
                ('headline', models.CharField(max_length=255, verbose_name='Headline')),
            ],
            options={
                'abstract': False,
            },
            bases=('sections.pagenode', models.Model),
        ),
        migrations.CreateModel(
            name='SectionList',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sections.pagenode',),
        ),
    ]
