# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0006_auto_20161212_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('pagenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.PageNode')),
                ('content', models.TextField(verbose_name='Content')),
                ('teaser', models.TextField(verbose_name='Teaser')),
                ('image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('sections.pagenode',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('pagenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.PageNode')),
                ('node_type', models.CharField(blank=True, max_length=128)),
                ('headline', models.CharField(max_length=255, verbose_name='Headline')),
            ],
            options={
                'abstract': False,
            },
            bases=('sections.pagenode', models.Model),
        ),
        migrations.CreateModel(
            name='SectionList',
            fields=[
                ('pagenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sections.PageNode')),
            ],
            options={
                'abstract': False,
            },
            bases=('sections.pagenode',),
        ),
    ]
